export const mockClaims = [
  {
    claim_id: 101,
    user_id: 1,
    user_name: "Alice Smith",
    title: "Business Trip to NYC",
    description: "Flight, hotel, and meals for conference.",
    total_amount: 1200.5,
    status: 1,
    status_text: "Pending",
  },
  {
    claim_id: 102,
    user_id: 2,
    user_name: "Bob Lee",
    title: "Client Dinner",
    description: "Dinner with client at The Grill.",
    total_amount: 230.0,
    status: 2,
    status_text: "Approved",
  },
  {
    claim_id: 103,
    user_id: 3,
    user_name: "Carol Tan",
    title: "Office Supplies",
    description: "Printer ink and paper.",
    total_amount: 75.99,
    status: 3,
    status_text: "Rejected",
  },
];

export const mockClaimDetail = {
  claim_id: 101,
  user_id: 1,
  user_name: "Alice Smith",
  title: "Business Trip to NYC",
  description: "Flight, hotel, and meals for conference.",
  total_amount: 1200.5,
  status: 1,
  status_text: "Pending",
  items: [
    {
      item_id: 1,
      category: "Flight",
      amount: 600,
      description: "Round trip flight",
      receipt: "receipt_flight.jpg",
      expense_date: "2025-06-10",
    },
    {
      item_id: 2,
      category: "Hotel",
      amount: 400,
      description: "3 nights hotel",
      receipt: "receipt_hotel.jpg",
      expense_date: "2025-06-11",
    },
    {
      item_id: 3,
      category: "Meals",
      amount: 200.5,
      description: "Meals during trip",
      receipt: "receipt_meals.jpg",
      expense_date: "2025-06-12",
    },
  ],
  approvals: [
    {
      approval_id: 1,
      level: 1,
      approver_id: 10,
      approver_name: "Manager Mike",
      decision: 1,
      comment: "Approved, all receipts attached.",
      decision_TIME: "2025-06-15 09:00:00",
    },
  ],
};
